modName=DynamicTreesRU
modId=dtru
modVersion=1.0.2
group=therealeststu.dtru

mcVersion=1.20.1
forgeVersion=47.2.0
mappingsChannel=parchment
mappingsVersion=2023.09.03-1.20.1

dynamicTreesVersion=1.4.5
dynamicTreesPlusVersion=1.2.1.002
jeiVersion=15.0.0.12
ccVersion=1.109.4
suggestionProviderFixVersion=1.0.0

versionType=release
versionRecommended=true
updateCheckerPath=Add-ons/RU.json

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false